CREATE TABLE `log_orders` (
  `id` int(11) NOT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `DATE` datetime DEFAULT NULL,
  `BASKET_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `BASKET_ID_FK` (`BASKET_ID`),
  CONSTRAINT `BASKET_ID_FK` FOREIGN KEY (`BASKET_ID`) REFERENCES `basket` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

